project/__init__.py
from flask import redirect, url_for, Blueprint, request, session
from flask import Flask, render_template
from pymongo import MongoClient

client = MongoClient('mongodb://localhost:27017/')
db = client['project']


def create_app():
    app = Flask(__name__, template_folder='templates', static_folder='static')
    

    from project.items import items
    app.register_blueprint(items, url_prefix='/items')
    from project.auth import auth
    app.register_blueprint(auth, url_prefix='/auth')
    from project.accounts import accounts
    app.register_blueprint(accounts, url_prefix='/accounts')
    from project.vendors import vendors
    app.register_blueprint(vendors, url_prefix='/vendors')
    from project.users import users
    app.register_blueprint(users, url_prefix='/users')


    @app.route('/')
    def index():
        if not session.get('name'):
                return redirect(url_for('auth.login'))
        return render_template("index.html")
    
    @app.route('/tech')
    def tech():
         return render_template('tech.html')

    return app



project/accounts/__init__.py
from flask import Blueprint
from pymongo import MongoClient

accounts = Blueprint('accounts', __name__, template_folder='templates', static_folder='static')

client = MongoClient('mongodb://localhost:27017/')
db = client['project']

from project.accounts import routes

project/accounts/routes.py
from project.accounts import accounts
from project.accounts import db
from flask import render_template, session, redirect, url_for

@accounts.route('/show')
def show():
    if 'id' not in session:
        return redirect(url_for('auth.login'))
    
    collection = db['accounts']
    print(session['id'])
    accs = collection.find({'ownerId': session['id']})
    acc_list = []
    for acc in accs:
        print(acc)
        acc_dict = {
            'name': acc['name'],
            'type': acc['type'],
            'is_negative_allowed': acc['negative'],
            'amount': acc['amount'],
        }
        acc_list.append(acc_dict)

    return render_template('accounts.html', accs = acc_list)

project/items/__init__.py
from flask import Blueprint
from pymongo import MongoClient

items = Blueprint('items', __name__, template_folder='templates', static_folder='static')

client = MongoClient('mongodb://localhost:27017/')
db = client['project']

from project.items import routes

project/items/routes.py
from project.items import items
from project.items import db
from flask import render_template, redirect, url_for, session


@items.route ('/show')
def show (limit=20):
    collection = db['items']
    items = collection.find().skip(skip=150).limit(limit)
    item_list = []
    for item in items:
        item_dict = {
            "id": item["_id"],
            "barcode": item["barcode"],
            "name": item["name"],
            "weight": item["weight"],
            "buying_price": item["buyingPrice"],
            "selling_price": item["sellingPrice"],
            "amount": item["amount"],
        }
        if item['weight'] == 'true':
            item_dict["weight"] = 'kg'
        else:
            item_dict["weight"] = 'units'
        if 'brandId' in item:
            item_dict["brandId"] = item["brandId"]
        if 'brandName' in item:
            item_dict["brandName"] = item["brandName"]
        if 'categoryName' in item:
            item_dict["categoryName"]= item["categoryName"]
        if 'categoryId' in item:
            item_dict["categoryId"]= item["categoryId"]
        #print(item_dict)
        item_list.append(item_dict)

    return render_template('items.html',  items=item_list)


@items.route('/delete/<barcode>')
def delete(barcode):
    if session['id'] is None:
        return redirect(url_for('auth.login'))
    collection = db['items']
    deletion = collection.delete_one({'barcode': barcode})
    return 

@items.route('/purchases')
def purchases():
    if session['id'] is None:
        return redirect(url_for('auth.login'))
    p_list = []

    return render_template('purchases.html', list=p_list)

project/users/__init__.py
from flask import Blueprint
from pymongo import MongoClient

users = Blueprint('users', __name__, template_folder='templates', static_folder='static')
client = MongoClient('mongodb://localhost:27017/')
db = client['project']


from project.users import routes

project/users/routes.py
from flask import render_template, request, session, flash, redirect, url_for
from project.users import users
from project.users import db

@users.route('/profile')
def profile():
    if session['name'] is None:
        redirect(url_for('login'))
    user = db['users'].find_one({'_id': session['id']})
    if request.method == 'GET':
        return render_template('profile.html', user=user)
    
    name = request.form.get('name')
    email = request.form.get('email')
    phone = request.form.get('phone')


    user = db['users'].find_one({'_id': session['id']})

    if user['name'] != name or user['email'] != email or user['phone_number'] != phone:
        user['name'] = name
        user['email'] = email
        user['phone'] = phone

        values = {
            "$set": {
            'name': name,
            'email':email,
            'phone':phone,
            }
        }

        db['users'].update_one({'_id': session['id']}, {})

    collection = db['users']
    user = collection.find({'_id': session['id']}, values)
    return render_template('profile.html', user=user)

project/vendors/__init__.py
from flask import Blueprint
from pymongo import MongoClient

vendors = Blueprint('vendors', __name__, template_folder='templates', static_folder='static')
client = MongoClient('mongodb://localhost:27017/')
db = client['project']

from project.vendors import routes

project/vendors/routes.py
from project.vendors import vendors
from project.vendors import db
from flask import render_template

@vendors.route('/show')
def show(limit=20):
    vendors = db.vendors.find().limit(limit=limit)
    vendor_list = []
    for v in vendors:
        v_dict = {
            'id': v['_id'],
            'name': v['name'],
            'type': v['type'],
            'contacts': v['contacts'],
        }
        vendor_list.append(v_dict)

    return render_template('vendors.html', list=vendor_list)

project/templates/auth.html
{% extends 'main_navless.html' %}

{% block links %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block body %}
    <div class="container vh-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                        {% block form %} {%endblock %}
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-5 d-flex align-items-center order-1 order-lg-2">
                        <img src="{{url_for('static', filename='img/main.png')}}" class="img-fluid" alt="Sample image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/templates/index.html
{% extends 'main.html' %}

{% block title %}
Nyrysk
{% endblock %}

{% block body  %}

{% endblock %}

project/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.2/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block links %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='img/icon.png') }}">

</head>
<nav>
    <a href="{{ url_for('index') }}">
        <img class="nav-link" src="{{ url_for('static', filename='img/main.png') }}" width="200" height="70">
    </a>
    <ul>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('tech')}}">Technologies we use</a></li>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{url_for('items.purchases')}}">Purchases</a></li>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('items.show') }}">Items</a></li>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('accounts.show')}}">Accounts</a></li>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('vendors.show') }}">Vendors</a></li>
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('users.profile') }}">Profile</a></li>
        {% if session['name'] %}
        <li><a style="position: relative; right:auto; top: -75px;" href="{{url_for('auth.logout')}}">Log out</a></li>
        {% else %}
        <li><a style="position: relative; right:auto; top: -75px;" href="{{ url_for('auth.login') }}">Login</a></li>
        {% endif %}
    </ul>

</nav>

<div id="page-container">
    <div style="margin-top: 50px;" id="content-wrap">
        {% block body %}
        {% endblock %}

    </div>
    <footer id="footer">
            <ul class="footer-ul">
                <li><a href="#" class="footer-li">Home</a></li>
                <li><a href="#" class="footer-li">About</a></li>
                <li><a href="#" class="footer-li">Contact</a></li>
            </ul>
    </footer>

    <div class="alerts position-fixed d-flex flex-column justify-content-center start-50 translate-middle-x"
        style="z-index: 1; top: 25%;">
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }} text-center px-5" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>
    </body>

</html>

project/templates/main_navless.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block links %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='img/icon.png') }}">
    
</head>
{% block body %}{% endblock %}

<div class="alerts position-fixed d-flex flex-column justify-content-center start-50 translate-middle-x"
     style="z-index: 1; top: 25%;">
    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ category }} text-center px-5" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>






   

project/templates/tech.html
{% extends 'main.html' %}
    {% block links %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.14.0/devicon.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">       
    <link rel="shortcut icon" href="bookmark.png" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='style1.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">    
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endblock %}

    {% block title %}Technologies{% endblock %}

{% block body %}
<h1 style="margin-left:100px;color: #219F94;margin-top: 40px">Technologies we use </h1>

<div style="margin-top: 30px"class="container">
  <div class="row align-items-start">
    <div class="col">
      <i style="font-size:128px" class="devicon-android-plain-wordmark"></i>
    </div>
    <div class="col">
      <i style="font-size:128px"  class="devicon-angularjs-plain-wordmark"></i>
    </div>
    <div class="col">
      <i style="font-size:128px"  class="devicon-ceylon-plain"></i>
    </div>
    <div class="col">
      <i style="font-size:128px" class="devicon-git-plain"></i>
    </div>
  </div>
  </div>
  
  <div class="container">
      <div class="row align-items-start">
        <div class="col">
          <i style="font-size:128px" class="devicon-nestjs-plain-wordmark"></i>
        </div>
        <div class="col">
          <i style="font-size:128px" class="devicon-visualstudio-plain-wordmark"></i>
        </div>
        <div class="col">
          <i style="font-size:128px"  class="devicon-pycharm-plain-wordmark"></i>
        </div>
        <div class="col">
          <i style="font-size:128px" class="devicon-swift-plain-wordmark"></i>
        </div>
    </div>
    </div>

    <div class="container">
      <div class="row align-items-start">
        <div class="col">
          <i style="font-size:128px;" class="devicon-tortoisegit-plain"></i>
        </div>
        <div class="col">
          <i style="font-size:128px" class="devicon-vagrant-plain-wordmark"></i>
        </div>
        <div class="col">
          <i style="font-size:128px"  class="devicon-yii-plain"></i>
        </div>
        <div class="col">
          <i style="font-size:128px" class="devicon-zig-original"></i>
        </div>
    </div>
    </div>
{% endblock %}